version: '2'
services:
  quanxian-app:
    image: quanxian
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://quanxian-mysql:3306/quanxian?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://quanxian-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://quanxian-elasticsearch:9200
    ports:
      - 8080:8080
  quanxian-mysql:
    extends:
      file: mysql.yml
      service: quanxian-mysql
  quanxian-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: quanxian-elasticsearch
